analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3408322,"name"\:"First Project","teamId"\:3380003,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3444732,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3380003,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
