<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_imgLogin</name>
   <tag></tag>
   <elementGuidId>32cd513e-3b1f-47a4-859e-dd19ce31646a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'imgLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd337533-34ff-4c4b-a1dc-bf72887ef218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>dd220810-5069-44c6-a20f-f8949354b758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imgLogin</value>
      <webElementGuid>c27ff9e5-2ab1-4beb-be84-e482d70d84d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgLogin</value>
      <webElementGuid>90eb4b03-14ba-428f-ad21-1b88b1a6dc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/btn_login.jpg</value>
      <webElementGuid>5ad55c00-6355-4b77-849b-0d931bf81f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return Validate();</value>
      <webElementGuid>f711bbb5-4896-481f-9774-90804a8e9de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a087cc1fd77f9eea4157cd5d2c0736c2</value>
      <webElementGuid>c720af10-8cba-4fd4-97eb-318fee85fe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'imgLogin']</value>
      <webElementGuid>4224b244-ce6c-4693-b2aa-6e650c355608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'imgLogin']</value>
      <webElementGuid>9e158aae-f682-4670-bac6-2160c0411c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'imgLogin' and @id = 'imgLogin' and @src = 'images/btn_login.jpg']</value>
      <webElementGuid>bdb1ffe8-aade-4f63-bc87-8f407d9dbd0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
