<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>7024adbe-ebb8-46e0-93cb-afa50dbfcf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtPwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'txtPwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f4611bb-c31d-403e-838f-5b988f9fc2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPwd</value>
      <webElementGuid>36cde9bd-6710-4d87-b393-515915e804e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a0465f94-80a8-4e51-889b-9b4eb59e2bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPwd</value>
      <webElementGuid>8e565a5a-b9cc-4603-83df-675bcddbe315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tBox</value>
      <webElementGuid>b56b2ecf-0372-4bf8-a37d-0107c3d25eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value=''</value>
      <webElementGuid>f06335b6-e0c3-4315-9114-a01c18861689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>988cb25b-5445-49fb-91bf-41af76d0506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-23d3fa5987ae87d8f5752583287421ee</value>
      <webElementGuid>a1de5f4c-1bbf-41af-b91c-a580ccfa4d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'txtPwd']</value>
      <webElementGuid>26d75ea8-8946-481c-8835-91d4bacc1ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'txtPwd']</value>
      <webElementGuid>b48e0dc0-5883-4d45-b5c9-a308d34633c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtPwd' and @type = 'password' and @id = 'txtPwd' and @placeholder = 'Password']</value>
      <webElementGuid>f19049fb-dad1-47a6-95ba-40c8454653a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
